### ISSUE TITLE
problem when running synthesize_convos

### ISSUE THREAD

**Issue by seoguypt** [daveshap/TutorChatbot#1]
Traceback (most recent call last):
  File "C:\TutorChatbot\synthesize_convos.py", line 55, in <module>
    tpc = topic.replace(' ', '').replace('(','').replace(')','').replace('-','').replace(',','').replace('"')[0:15]
TypeError: replace expected at least 2 arguments, got 1

**Comment by daveshap** [comment]
Looks like the last replace is fat-fingered. You can just remove it or correct it. I will update momentarily.
